### ISSUE TITLE
Support `notag`

### ISSUE THREAD

**Issue by jfkhoury** [jfkhoury/react-responsive-component#1]
Add a `notag` prop to not generate a container.

``` html
<ResponsiveComponent notag="true">
...
```

which will render the children only.

**Comment by donavon** [comment]
You can't return fragments (at least in 15.0.x). See https://github.com/facebook/react/issues/2127

**Comment by donavon** [comment]
@jfkhoury What do you say about if you do `tag=""` and there is a single child, it passes the child straight through, but if there are multiple children, it throws?

**Comment by jfkhoury** [comment]
@donavon I worry that it won't be clear enough. It doesn't sound like the `notag` is really necessary anyway :) I might close this issue and we will reopen it if the children asks for it.
